# Generated by Django 2.0.3 on 2019-12-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='houseintro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=50, verbose_name='此小区名称')),
                ('house_type', models.CharField(max_length=20, verbose_name='户型')),
                ('house_size', models.CharField(max_length=8, verbose_name='平米数')),
                ('house_high_message1', models.CharField(max_length=3, verbose_name='共几层')),
                ('house_high_message2', models.CharField(max_length=3, verbose_name='第几层')),
                ('house_rent_money', models.CharField(max_length=10, verbose_name='租金/每月')),
                ('house_facility', models.CharField(max_length=500, verbose_name='设施简介')),
                ('house_renter_phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('img_url', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': '房屋信息表',
                'db_table': 'houseintro',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('rentorsell', models.BooleanField(default=False, verbose_name='用户类型')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('identifyid', models.CharField(max_length=18, verbose_name='身份证')),
                ('address', models.CharField(max_length=30, verbose_name='邮箱地址')),
                ('email', models.CharField(max_length=20, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
