# Generated by Django 2.2.8 on 2019-12-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseintro',
            name='house_ts',
            field=models.CharField(max_length=2, null=True, verbose_name='特色'),
        ),
    ]
