# Generated by Django 2.2.8 on 2019-12-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_houseintro_house_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseintro',
            name='house_ts',
            field=models.CharField(max_length=100, null=True, verbose_name='特色'),
        ),
    ]
